In [1]:
import numpy as np

cost = np.array([
    [2, 3, 1],
    [5, 4, 8],
    [5, 6, 8]
])

supply = [30, 40, 20]
demand = [20, 30, 40]

allocation = np.zeros((3,3), dtype=int)

i = 0
j = 0

while i < len(supply) and j < len(demand):

    x = min(supply[i], demand[j])

    allocation[i][j] = x

    supply[i] -= x
    demand[j] -= x

    if supply[i] == 0:
        i += 1
    elif demand[j] == 0:
        j += 1

print("Allocation Matrix:")
print(allocation)

total_cost = np.sum(allocation * cost)

print("\nTotal Transportation Cost =", total_cost)


Allocation Matrix:
[[20 10  0]
 [ 0 20 20]
 [ 0  0 20]]

Total Transportation Cost = 470
